batfish/batfish.github.io

_config.yml

Add google analytics tracking code.

add tracking code

---

_layouts/home.html

improve appearance between screen-width: 767px and 991px

Improve breakpoints

---

_layouts/home.html

add second round of videos

---

_layouts/home.html

add Analyzing ACLs and Firewall Rules playlist link

---

_layouts/home.html

add link to Introduction to Forwarding Change Validation video

---

.gitignore
_config.yml
_layouts/default.html
_layouts/home.html
_sass/_sections.scss
_sass/_variables.scss
package-lock.json
package.json

- Non-carousel content changes. 
- Adding auto-format on save. 
- Reformatting code to make adding videos easier.

Carousel video embedding

---

_layouts/home.html

Also remove old NANOG talks. New one should be added here later.

Make a section for community resources

---

_includes/tutorial_carousel.html
_layouts/default.html
_layouts/home.html
_sass/_sections.scss
_sass/_typography.scss
assets/js/carousel-section.js

Use video carousel instead of links

---

.vscode/settings.json
_includes/banner.html
_includes/disqus_comments.html
_includes/google-analytics.html
_includes/head.html
_includes/header.html
_includes/publications.html
_includes/tutorial_carousel.html
_layouts/default.html
_layouts/home.html
_layouts/post.html
_sass/_media-queries.scss
_sass/_overrides.scss
_sass/_sections.scss
_sass/_typography.scss

Format on save. 
Ignore the generated `/docs` directory 
Format files

Add formatting

---

_includes/publications.html
_includes/tutorial_carousel.html
_layouts/home.html
_sass/_media-queries.scss

Since small screens do not present the carousel well,  I suggest we go back to presenting links when viewed from a small device

Better mobile experience

---

_layouts/home.html
_sass/_media-queries.scss
_sass/_sections.scss

* add comments to media queries
* vertically collapse text and batfish sooner
We vertically collapse the two containers sooner to avoid an awkward state.

improve alignment betwen batfish and text

---

_layouts/home.html

Unleashing the Batfish

---

_layouts/home.html

Unleashing the Batfish part 2

---

_includes/community-resources.html
_layouts/home.html
_sass/_media-queries.scss
assets/js/custom.js

split up community resources by media type

---

_includes/community-resources.html

Delete spare `|`

---

_includes/banner.html

fix slack pointer

---

_includes/community-resources.html

about using Batfish and Ansible for multi-tiered firewall analysis.

Link to new Packetflow Blog

---

_includes/community-resources.html

Added link to packetflow blog part 3

Packetflow blog part 3

---

_includes/community-resources.html

Add Rick Donato's ACL auditor blog post to community resources

Add Rick D's blog to community resources

---

_config.yml
_includes/head.html
_layouts/page.html
_pages/firewall_analysis.html
_sass/_misc.scss
_sass/_sections.scss
_sass/_variables.scss

A dedicated page for firewall analysis.

Add fw page

---

_includes/head.html
_pages/firewall-analysis.html

Implementing some of the suggestions to improve SEO.
- still need to add backlinks to batfish.org from this page as well as add a link from batfish.org to this page (will do that in a separate PR)

Seo changes

---

.github/workflows/pre-commit.yml

pre-commit: add missing checkout

---

.github/workflows/pre-commit.yml

pre-commit: add upload artifact for checking
